<a href="https://colab.research.google.com/github/sangeetaisaac/Machine-Learning/blob/main/Liner_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## Vectors

```
# A Vector in Python is a one dimensional array of lists
```



In [ ]:
mylist = [1, 2, 3]

myVect = np.array(mylist)
print("Printing the vector")
print(myVect)

Printing the vector
[1 2 3]


#Horizontal and Verical vectors

In [ ]:
lst1 = [1,2,3,4,5]
lst2 = [[1], [2], [3], [4], [5]]
horVector = np.array(lst1)
vertVector = np.array(lst2)
print("Horizontal Vector created from list: ")
print(horVector)
print("Vertical Vector created from list: ")
print(vertVector)

Horizontal Vector created from list: 
[1 2 3 4 5]
Vertical Vector created from list: 
[[1]
 [2]
 [3]
 [4]
 [5]]


#Vector Operations
###Addition
###Subtraction
###Multiplication
###Division
###Operation with scalars

In [ ]:
#Addition of 2 dimensional vectors in the same direction

vect1 = np.array([2,2])
vect2 = np.array([3,3])
vecSum = vect1 + vect2
vecDiff = vect1 - vect2
vecProd = vect1 * vect2
vecDiv = vect1 / vect2
scalarVect = vect2 * 5

print("Vector Sum:")
print(vecSum)
print("Vector Difference:")
print(vecDiff)
print("Vector Product:")
print(vecProd)
print("Vector Division:")
print(vecDiv)
print("Scalar operation:")
print(scalarVect)

Vector Sum:
[5 5]
Vector Difference:
[-1 -1]
Vector Product:
[6 6]
Vector Division:
[0.66666667 0.66666667]
Scalar operation:
[15 15]


#Calculate the Norm (Magnitude) of A Vector

In [ ]:
#Calculate using math libraries
import numpy as np
import math

x = np.array([2,8])
norm = math.sqrt(x[0]** 2 + x[1]**2)
print(norm)

#Calculate using numpy libraries
norm2 = np.linalg.norm(x)
print(norm2)

8.246211251235321
8.246211251235321


# Calculate the distance between vectors (Useful for k-means clusters)

In [ ]:
a = np.array([10,3])
b = np.array([3,7])

norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
dist = np.linalg.norm(a - b)
print(norm_a)
print(norm_b)
print(dist)

10.44030650891055
7.615773105863909
8.06225774829855


# Calculate the dot product of 2 vectors

In [ ]:
u = np.array([3,7])
v = np.array([10,3])

dot_uv = u[0]*v[0] + u[1]*v[1]
dot_uv_alt = np.dot(u, v)

print(dot_uv)
print(dot_uv_alt)


51
51


# Dot product of perpendicular vectors
#### The Dot product of perpedicular vectors is 0 - They are orthogonal vectors

In [ ]:


u1 = np.array([0,4])
v1 = np.array([4,0])

dot_u1v1 = np.dot(u1, v1)
print(dot_u1v1)

0


# calculate the angle between 2 vectors

In [ ]:
a = np.array([10,3,2,3])
b = np.array([3,7,4,5])

theta = math.acos(np.dot(a,b)/(np.linalg.norm(a) * np.linalg.norm(b)))
print(f"Angle= {theta} rads")

Angle= 0.8320796291729496 rads


#Calculate the cross product and the magnitude of the cross product

In [ ]:
c = np.array([1,2,5])
d = np.array([2,-4,5])

cross_prod_cd = np.cross(c,d)
print(f"c X d = {cross_prod_cd}")

mag_cross_cd = np.linalg.norm(cross_prod_cd)
print(f"|c X d| = {mag_cross_cd}")

c X d = [30  5 -8]
|c X d| = 31.448370387032774


# Calculate the projection of vector e over f

In [ ]:
e = np.array([1, -2, 3])
f = np.array([2, 4, 5])

#Calculate the magnitude of the projection
mag_proj = np.dot(e,f)/np.linalg.norm(f)

#Calculate the projection
print(mag_proj/np.linalg.norm(f))
proj = ((mag_proj/np.linalg.norm(f))*f)
print(proj)

0.19999999999999998
[0.4 0.8 1. ]


#Matrix operations - Addition


In [ ]:
A = np.array([[1,2],[2,4]])
B = np.array([[10,1],[5,3]])

C = A + B
print(C)

[[11  3]
 [ 7  7]]


#Scalar Multiplication

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(5*A)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


# Matrix Multiplication

In [ ]:
A = np.array([[1,2], [2,1]])
B = np.array([[2,1], [1,2]])

# Calculate the matrix multiplication
C = np.matmul(A, B)
D = np.matmul(B, C)
print(f"A*B: {C}")
print(f"B(AB): {D}")

A*B: [[4 5]
 [5 4]]
B(AB): [[13 14]
 [14 13]]


#Determinant of a Matrix
###Scalar value computed from a Square Matrix. Used to determine if the matrix can have an inverse matrix.

In [8]:
import numpy as np

U = np.array([[3, 7, 0], [8, 0, -2], [0, -4, -5]])
det_U = np.linalg.det(U)
print(f"Determinant = {round(det_U)}")

Determinant = 256


#Rank of a Matrix
###Rank of a matrix helps you understand how many rows/columns are unique. Rank is closely related to determinant.

In [4]:
import numpy as np

V = np.array([[2,1],[4,2]])
rank = np.linalg.matrix_rank(V)
print(rank)


1


#Row Echolon Form to Find Rank (and solve linear equations)
###Simple row transformations to represent a matrix in their simplest versions

In [7]:
from sympy import *
A = Matrix([[1,2,1],[-2,-3,1],[3,5,0],[2,4,2]])
print(A)
B = A.rref()
print(B)

Matrix([[1, 2, 1], [-2, -3, 1], [3, 5, 0], [2, 4, 2]])
(Matrix([
[1, 0, -5],
[0, 1,  3],
[0, 0,  0],
[0, 0,  0]]), (0, 1))


##Transpose of a Matrix
###Operation that flips the matrix over its diagonal

In [1]:
import numpy as np

matrix = np.array([[1,2],[3,4]])

#calculate the transpose of the matrix
transpose_matrix = np.transpose(matrix)
transpose_of_transpose = np.transpose(transpose_matrix)

print(f"Transposed Matrix =\n {transpose_matrix}")
print(f"Transpose of transposed matrix =\n {transpose_of_transpose}")

Transposed Matrix =
 [[1 3]
 [2 4]]
Transpose of transposed matrix =
 [[1 2]
 [3 4]]


#Inverse of a Matrix
###Inverse of a square matrix is another matrix A^-1 which when multiplied by A gives Identity matrix I

In [4]:
A = np.array([[2,1], [7,4]])
AInv = np.linalg.inv(A)
print(AInv)

[[ 4. -1.]
 [-7.  2.]]
