<a href="https://colab.research.google.com/github/sangeetaisaac/Machine-Learning/blob/main/Pandas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Create a 1-d array
arr_1d = np.array([1,2,3,4,5])

print(arr_1d)

[1 2 3 4 5]


In [ ]:
#Get the shape, size and dimension of the 1 d array
print(arr_1d.shape)
print(arr_1d.ndim)
print(arr_1d.size)

(5,)
1
5


In [ ]:
#Create a random array of 5 consecutive values
arr_range = np.arange(5)
print(arr_range)

[0 1 2 3 4]


In [ ]:
#Create a 1-d array with 6 random integers between 1 and 9

arr_rand_int = np.random.randint(1,9,6)
print(arr_rand_int)

[6 1 3 1 7 5]


In [ ]:
#Create a 1-d array with 7 random floats between 0 and 1
arr_rand_float = np.random.random(7)
print(arr_rand_float)

[0.29755192 0.44322791 0.33054253 0.13082657 0.13317428 0.32455442
 0.7291203 ]


In [ ]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
arr_rand_2d = np.random.randint(0,10,(3,3))
print(arr_rand_2d)

[[3 8 0]
 [4 5 9]
 [1 9 8]]


In [ ]:
#Create an array of 5 zeros
arr_zeros = np.zeros(5, dtype=int)
print(arr_zeros)

[0 0 0 0 0]


In [ ]:
#create a 2-d array
arr_2d = np.array([
                [1,2],
                [3,4],
                [5, 6],
                [7,8]
                ])
print(arr_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#Create a random 2-d array

arr_rand_2d = np.random.rand(3,4)
print(arr_rand_2d)

[[0.90936839 0.66494738 0.33450124 0.84989624]
 [0.35163032 0.76098339 0.89880411 0.90055597]
 [0.43824894 0.99111776 0.76469853 0.9908339 ]]


In [ ]:
#Create a random 2-d array of integers of 4 rows and 5 columns

arr_int_2d = np.random.randint(1,10,(4,5))
print(arr_int_2d)

[[2 5 4 3 3]
 [6 9 7 6 6]
 [2 7 9 6 2]
 [7 7 7 8 5]]


In [ ]:
#Create a 3x5 floating-point array filled with 1s
arr_ones = np.ones((3,5), dtype=np.float32)
print(arr_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a 3x5 array filled with 3.14
arr_pi = np.full((3,5),3.14)
print(arr_pi)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [ ]:
# Create an array of five values evenly spaced between 0 and 10
arr_spaced = np.linspace(0,10,5)
print(arr_spaced)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#Get the shape, size and dimension of the 2 d array
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.size)

(4, 2)
2
8


In [ ]:
#Create a numpy array of float datatype
arr_float = np.array([2,4,5,6,7], dtype=np.float32)
print(arr_float)

[2. 4. 5. 6. 7.]


In [ ]:
 # Create a 3x3 identity matrix
arr_identity = np.eye(3,3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create random arrays with a default seed
rng = np.random.default_rng(seed=1561)

arr_1d_rand = rng.integers(10, size=6)
arr_2d_rand = rng.integers(10, size=(2,5))
print(arr_1d_rand)
print(arr_2d_rand)

[2 4 7 2 5 6]
[[4 4 0 1 4]
 [4 5 6 4 7]]


In [ ]:
# Create a 1-d array of size 6 of consecutive integers
arr_original = np.arange(6)
# Reshape it to 2X3
arr_reshape = arr_original.reshape(2,3)
print(arr_original)
print(arr_original.ndim)
print(arr_original.shape)
print(arr_reshape)
print(arr_reshape.ndim)
print(arr_reshape.shape)

[0 1 2 3 4 5]
1
(6,)
[[0 1 2]
 [3 4 5]]
2
(2, 3)


In [ ]:
arr_original_2 = np.array([[1,2,3],
                          [5,6,7]])
arr_reshape_2 = arr_original_2.reshape(3,-1)
print(arr_original_2)
print(arr_reshape_2)

[[1 2 3]
 [5 6 7]]
[[1 2]
 [3 5]
 [6 7]]


In [ ]:
#Use np.newaxis to reshape array along an axis and get vector
array_1d_ori = np.array([1,2,3])

row_vector_reshaped = array_1d_ori[np.newaxis, :]
column_vector_reshaped = array_1d_ori[:, np.newaxis]

In [ ]:
account_length = np.array([10,7,89,104,6,50,23])
print(account_length)

#print the first element
print(account_length[0])

#print the last element
print(account_length[-1])

#Display the even indexed elements
print(account_length[::2])

#Display the array in reverse order
print(account_length[::-1])

#Display the elements greater than 25 and less than 90
filter = (account_length > 25) & (account_length < 90)
print(filter)
print(account_length[filter])

[ 10   7  89 104   6  50  23]
10
23
[10 89  6 23]
[ 23  50   6 104  89   7  10]
[False False  True False False  True False]
[89 50]


In [ ]:
#Create a 2d array
array_2d_original = np.array([
                  [1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [-1,-2,-3,-4]
                  ])

#Get the first element of the array
print(array_2d_original[0][0])

#Get the first row of the array
print(array_2d_original[0, :])

#Get the second column of the array
print(array_2d_original[: , 1])

#Get sub-matrix of the array
print(array_2d_original[2:,2:])

1
[1 2 3 4]
[ 2  6 10 -2]
[[11 12]
 [-3 -4]]


In [ ]:
#Create a copy of the 2d array
arr_2d_copy = array_2d_original.copy()

#Modify an element in the copied array
arr_2d_copy[2][3] = 100
#Display the 2 arrays that show the value was not modified in the original array
print(arr_2d_copy)
print(array_2d_original)

[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11 100]
 [ -1  -2  -3  -4]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [-1 -2 -3 -4]]


In [ ]:
#Create a filter to display the odd indexed values of the 2 D array
filter_odd_elements = (array_2d_original % 2 != 0)
print(filter_odd_elements)
print(array_2d_original[filter_odd_elements])

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[ 1  3  5  7  9 11 -1 -3]


In [ ]:
#Concatenate multiple arrays
x = np.array([3,4,5,6])
y= np.array([1,2,3,4])
z = np.concatenate([x,y])
print(z)

[3 4 5 6 1 2 3 4]


In [ ]:
#Concatenate 2-d arrays along the x-axis using
arr_1 = np.array([[1,2,3,4], [5,6,7,8]])
arr_2 = np.array([[9,10,11,12], [13,14,15,16]])
print(np.concatenate([arr_1,arr_2]))
print(np.concatenate([arr_1,arr_2], axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
#Use vstack and hstack to join mixed dimension arrays
grid_1 = np.array([-1,-2,-3, -4])
print(np.vstack([arr_1, grid_1]))
grid_2 = np.array([[-1],
                  [-2]])
print(np.hstack([arr_1, grid_2]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 -2 -3 -4]]
[[ 1  2  3  4 -1]
 [ 5  6  7  8 -2]]


In [ ]:
#Splitting of arrays
arr_to_split = np.arange(10)
arr1, arr2, arr3 = np.split(arr_to_split, [3,5])
print(arr_to_split)
print(arr1, arr2, arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2] [3 4] [5 6 7 8 9]


In [ ]:
#Use vsplit and hsplit to split multi-dimensional arrays
multi_array = np.arange(16).reshape(4,4)
print(multi_array)
upper, lower = np.vsplit(multi_array, [2])
left, right = np.hsplit(multi_array,[2])
print(upper)
print(lower)
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
#Adding a scalar value to a 2-d array using for loops

input_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

def add_ten(arr_1d):
  output_array = np.empty_like(arr_1d)
  for row_idx in range(len(arr_1d)):
    for col_idx in range(len(arr_1d[row_idx])):
      output_array[row_idx,col_idx] = arr_1d[row_idx,col_idx] + 10
  print(output_array)
add_ten(input_array)

#alternatively you can use broadcasting, which is faster
out_array_broadcast = input_array + 10
print(out_array_broadcast)

[[11 12 13 14 15]
 [16 17 18 19 20]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#Broadcasting the sum of 1d array with 2d array
output_array_sum = out_array_broadcast + np.array([10,20,30,40,50])
output_array_prod = out_array_broadcast * np.array([10,20,30,40,50])
print(output_array_sum)
print(output_array_prod)

[[21 32 43 54 65]
 [26 37 48 59 70]]
[[ 110  240  390  560  750]
 [ 160  340  540  760 1000]]


In [ ]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)
print(M + a)

c = np.arange(3).reshape((3, 1))
d = np.arange(3)
print(c)
print(d)
print(c + d)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]
[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#Calculate the cross product

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.cross(arr1, arr2)

print(result)

[-3  6 -3]


In [ ]:
# Write a Python program using NumPy to create a 5x5 matrix filled with random integers between 1 and 100. Calculate the mean and standard deviation of the matrix and print them.

import numpy as np

arr1 = np.arange(1,100,4).reshape(5,5)
print(arr1)
print(arr1.mean())
print(arr1.std())

[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]
49.0
28.844410203711913


In [ ]:
#Using NumPy, create a 1000-element array of random integers between 1 and 1000. Calculate the cumulative sum of the array and print the 10th, 100th, and 500th elements of the cumulative sum array.
np.random.seed(0)
rand_nump = np.random.randint(1,1001,1000)

total_sum = np.cumsum(rand_nump)
print("10th Element of cumulative sum array", total_sum[9])
print("100th Element of cumulative sum array", total_sum[99])
print("500th Element of cumulative sum array", total_sum[499])

10th Element of cumulative sum array 5470
100th Element of cumulative sum array 52497
500th Element of cumulative sum array 253546


In [ ]:
# Write a Python program using NumPy to create a 10x10 matrix filled with random integers between 1 and 100. Find the minimum and maximum values of the matrix along with their indices.
rand_integer_array = np.random.randint(1, 101, (10,10))
min_value = np.min(rand_integer_array)
max_value = np.max(rand_integer_array)
min_index = np.unravel_index(np.argmin(rand_integer_array),(10, 10))
max_index = np.unravel_index(np.argmax(rand_integer_array),(10, 10))

print(rand_integer_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("Index of minimum value", min_index)
print("Index of maximum value", max_index)

[[ 29  96  66  81  83  15  22  70  34   3]
 [ 28  20  16  72  30  36  98  49  50  81]
 [ 57  64  89  59   6  52  62  84  18  46]
 [ 97  63  23  98  10   6  77  62  43  17]
 [ 60  18  69  61  26  15  62  54  82  30]
 [ 71  29  75   6  85  56  51  87  54  11]
 [ 44  60  31  60  15  49  57  66   8  70]
 [ 16  53  33  88  79  35  30  52  90  54]
 [  5  65  27  85   6  89  18  69  57  33]
 [ 82  73  74  32  95  74  49 100  33  15]]
Minimum Value: 3
Maximum Value: 100
Index of minimum value (0, 9)
Index of maximum value (9, 7)
